// Generated by CoffeeScript 1.10.0
(function() {
  var Handlers, debug, pubsub;

  pubsub = require('./PubSub');

  debug = require('debug')('xbmc:Handlers');

  Handlers = (function() {
    function Handlers() {}

    Handlers.mixin = function(api) {
      var method, name;
      this.api = api;
      debug('mixin');
      this.api.handlers = {};
      for (name in this) {
        method = this[name];
        this.api.handlers[name] = method;
      }
      return delete this.api.handlers.mixin;
    };

    Handlers.players = function(data) {
      var dfd, playerId, ref;
      debug('players', data);
      playerId = (((ref = data.result) != null ? ref[0] : void 0) || data.player || {}).playerid;
      if (playerId) {
        dfd = Handlers.api.send('Player.GetItem', {
          playerid: playerId
        });
        return dfd.then(Handlers.playerItem);
      }
    };

    Handlers.playerItem = function(data) {
      var fn;
      debug('playerItem', data);
      if (!data.result.item.id) {
        return pubsub.emit('api:video', data.result.item);
      } else {
        data = data.result.item;
        fn = Handlers.api.media[data.type];
        if (fn) {
          return fn(data.id);
        } else {
          return console.log('Unhandled played item:', data);
        }
      }
    };

    return Handlers;

  })();

  module.exports = Handlers;

}).call(this);
