// Generated by CoffeeScript 1.10.0
(function() {
  var i, len, mod, ref;

  module.exports = {};

  ref = ['XbmcApi', 'TCPConnection', 'Player', 'Input', 'Handlers', 'Media', 'Notifications'];
  for (i = 0, len = ref.length; i < len; i++) {
    mod = ref[i];
    module.exports[mod] = require("./" + mod);
  }

  module.exports.pubsub = require('./PubSub');

}).call(this);
