// Generated by CoffeeScript 1.6.3
(function() {
  var mod, _i, _len, _ref;

  module.exports = {};

  _ref = ['XbmcApi', 'TCPConnection', 'Player', 'Input', 'Handlers', 'Media', 'Notifications'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    mod = _ref[_i];
    module.exports[mod] = require("./" + mod);
  }

  module.exports.pubsub = require('./PubSub');

}).call(this);
