// Generated by CoffeeScript 1.4.0
(function() {
  var Input, pubsub, _fn, _i, _key, _len, _ref;

  pubsub = require('./PubSub');

  Input = (function() {

    function Input() {}

    Input.mixin = function(api) {
      var method, name;
      Input.api = api;
      api.input = {};
      for (name in Input) {
        method = Input[name];
        api.input[name] = method;
      }
      return delete api.input.mixin;
    };

    return Input;

  }).call(this);

  _ref = ['Up', 'Down', 'Left', 'Right', 'Select', 'SendText', 'ShowCodec', 'ShowOSD', 'Info', 'Home', 'Down', 'ContextMenu', "Back"];
  _fn = function() {
    var key, key_lower;
    key = _key;
    key_lower = key.toLowerCase();
    return Input[key_lower] = function(fn) {
      var dfd;
      if (fn == null) {
        fn = null;
      }
      dfd = this.api.send("Input." + key);
      return dfd.then(function(data) {
        pubsub.emit("input." + key_lower, data);
        if (fn) {
          return fn(data);
        }
      });
    };
  };
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    _key = _ref[_i];
    _fn();
  }

  module.exports = Input;

}).call(this);
