// Generated by CoffeeScript 1.4.0
(function() {
  var Player, pubsub;

  pubsub = require('./PubSub');

  Player = (function() {

    function Player() {}

    Player.mixin = function(api) {
      var method, name;
      this.api = api;
      api.player = {};
      for (name in this) {
        method = this[name];
        api.player[name] = method;
      }
      return delete api.player.mixin;
    };

    Player.open = function(item, options, fn) {
      var dfd;
      if (options == null) {
        options = {};
      }
      if (fn == null) {
        fn = null;
      }
      dfd = Player.api.send('Player.Open', {
        item: item,
        options: options
      });
      return dfd.then(function(data) {
        pubsub.emit('player.open', data);
        if (fn) {
          return fn(data);
        }
      });
    };

    Player.openYoutube = function(id, options, fn) {
      var item;
      if (options == null) {
        options = {};
      }
      if (fn == null) {
        fn = null;
      }
      item = {
        file: "plugin://plugin.video.youtube/?action=play_video&videoid=" + id
      };
      return Player.open(item, options, fn);
    };

    Player.openFile = function(file, options, fn) {
      var item;
      if (options == null) {
        options = {};
      }
      if (fn == null) {
        fn = null;
      }
      item = {
        file: file
      };
      return Player.open(item, options, fn);
    };

    return Player;

  }).call(this);

  module.exports = Player;

}).call(this);
