// Generated by CoffeeScript 1.10.0
(function() {
  var EventEmitter, PubSub, debug, pubsub,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EventEmitter = require('events').EventEmitter;

  debug = require('debug')('xbmc:PubSub');

  PubSub = (function(superClass) {
    extend(PubSub, superClass);

    function PubSub() {
      debug('constructor');
      PubSub.__super__.constructor.apply(this, arguments);
    }

    return PubSub;

  })(EventEmitter);

  pubsub = new PubSub();

  module.exports = pubsub;

}).call(this);
