// Generated by CoffeeScript 1.4.0
(function() {
  var EventEmitter, PubSub, pubsub,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  PubSub = (function(_super) {

    __extends(PubSub, _super);

    function PubSub() {
      PubSub.__super__.constructor.apply(this, arguments);
    }

    return PubSub;

  })(EventEmitter);

  pubsub = new PubSub();

  module.exports = pubsub;

}).call(this);
