// Generated by CoffeeScript 1.10.0
(function() {
  var Connection, clarinet, debug, defer, net, pubsub,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  debug = require('debug')('xbmc:TCPConnection');

  pubsub = require('./PubSub');

  defer = require('node-promise').defer;

  clarinet = require('clarinet');

  net = require('net');

  Connection = (function() {
    function Connection(options) {
      var base, base1, base2, base3, base4, base5;
      this.options = options != null ? options : {};
      this._receive = bind(this._receive, this);
      this._createParser = bind(this._createParser, this);
      this.onData = bind(this.onData, this);
      this.onClose = bind(this.onClose, this);
      this.onError = bind(this.onError, this);
      this.onOpen = bind(this.onOpen, this);
      this.publish = bind(this.publish, this);
      this.close = bind(this.close, this);
      this.send = bind(this.send, this);
      this.isActive = bind(this.isActive, this);
      this.create = bind(this.create, this);
      debug('constructor', this.options);
      if ((base = this.options).port == null) {
        base.port = 9090;
      }
      if ((base1 = this.options).host == null) {
        base1.host = '127.0.0.1';
      }
      if ((base2 = this.options).user == null) {
        base2.user = 'xbmc';
      }
      if ((base3 = this.options).password == null) {
        base3.password = false;
      }
      if ((base4 = this.options).verbose == null) {
        base4.verbose = false;
      }
      if ((base5 = this.options).connectNow == null) {
        base5.connectNow = true;
      }
      this._createParser();
      this.sendQueue = [];
      this.deferreds = {};
      if (this.options.connectNow) {
        this.create();
      }
    }

    Connection.prototype.create = function() {
      debug('create');
      this.socket = net.connect({
        host: this.options.host,
        port: this.options.port
      });
      this.socket.on('connect', this.onOpen);
      this.socket.on('data', this.onData);
      this.socket.on('error', this.onError);
      this.socket.on('disconnect', this.onClose);
      return this.socket.on('close', this.onClose);
    };

    Connection._id = 0;

    Connection.generateId = function() {
      return "__id" + (++Connection._id);
    };

    Connection.prototype.isActive = function() {
      var ref;
      debug('isActive');
      return ((ref = this.socket) != null ? ref._connecting : void 0) === false;
    };

    Connection.prototype.send = function(data) {
      var base, dfd, name;
      if (data == null) {
        data = null;
      }
      debug('send', JSON.stringify(data));
      if (!data) {
        throw new Error('Connection: Unknown arguments');
      }
      if (data.id == null) {
        data.id = Connection.generateId();
      }
      dfd = (base = this.deferreds)[name = data.id] != null ? base[name] : base[name] = defer();
      if (!this.isActive()) {
        this.sendQueue.push(data);
      } else {
        data.jsonrpc = '2.0';
        data = JSON.stringify(data);
        this.publish('send', data);
        this.socket.write(data);
      }
      return dfd.promise;
    };

    Connection.prototype.close = function(fn) {
      var err, error;
      if (fn == null) {
        fn = null;
      }
      debug('close');
      try {
        this.socket.end();
        this.socket.destroy();
        if (fn) {
          return fn();
        }
      } catch (error) {
        err = error;
        this.publish('error', err);
        if (fn) {
          return fn(err);
        }
      }
    };

    Connection.prototype.publish = function(topic, data) {
      var dataVerbose;
      if (data == null) {
        data = {};
      }
      dataVerbose = typeof data === 'object' ? JSON.stringify(data) : data;
      debug('publish', topic, dataVerbose);
      return pubsub.emit("connection:" + topic, data);
    };

    Connection.prototype.onOpen = function() {
      debug('onOpen');
      this.publish('open');
      return setTimeout(((function(_this) {
        return function() {
          var i, item, len, ref;
          ref = _this.sendQueue;
          for (i = 0, len = ref.length; i < len; i++) {
            item = ref[i];
            _this.send(item);
          }
          return _this.sendQueue = [];
        };
      })(this)), 500);
    };

    Connection.prototype.onError = function(evt) {
      debug('onError', JSON.stringify(evt));
      return this.publish('error', evt);
    };

    Connection.prototype.onClose = function(evt) {
      debug('onClose', evt);
      this.publish('close', evt);
      return this.parser.close();
    };

    Connection.prototype.onData = function(buffer) {
      debug('onData');
      return this.parser.write(buffer.toString());
    };

    Connection.prototype._createParser = function() {
      var addValue, currentKey, publish, stack;
      this.parser = clarinet.parser();
      stack = [];
      currentKey = null;
      publish = this.publish;
      addValue = (function(_this) {
        return function(val) {
          if (Array.isArray(stack[0])) {
            return stack[0].push(val);
          } else {
            return stack[0][currentKey] = val;
          }
        };
      })(this);
      this.parser.onerror = (function(_this) {
        return function(ex) {
          return publish('error', ex);
        };
      })(this);
      this.parser.onvalue = (function(_this) {
        return function(val) {
          return addValue(val);
        };
      })(this);
      this.parser.onopenobject = (function(_this) {
        return function(key) {
          var obj;
          obj = {};
          if (stack.length) {
            addValue(obj);
          }
          stack.unshift(obj);
          return currentKey = key;
        };
      })(this);
      this.parser.onkey = (function(_this) {
        return function(key) {
          return currentKey = key;
        };
      })(this);
      this.parser.oncloseobject = (function(_this) {
        return function() {
          var obj;
          obj = stack.shift();
          if (stack.length === 0) {
            return _this._receive(obj);
          }
        };
      })(this);
      this.parser.onopenarray = (function(_this) {
        return function() {
          var arr;
          arr = [];
          if (stack.length) {
            addValue(arr);
          }
          return stack.unshift(arr);
        };
      })(this);
      this.parser.onclosearray = (function(_this) {
        return function() {
          return stack.shift();
        };
      })(this);
      return this.parser.onend = (function(_this) {
        return function() {};
      })(this);
    };

    Connection.prototype._receive = function(data) {
      var dfd, evt, id, ref, ref1;
      evt = {
        data: data
      };
      id = (ref = evt.data) != null ? ref.id : void 0;
      dfd = this.deferreds[id];
      delete this.deferreds[id];
      if (evt.data.error) {
        this.onError(evt);
        if (dfd) {
          return dfd.reject(evt.data);
        }
      } else {
        this.publish('data', evt.data);
        if ((ref1 = evt.data.method) != null ? ref1.indexOf('.On' > 1) : void 0) {
          this.publish('notification', evt.data);
        }
        if (dfd) {
          return dfd.resolve(evt.data);
        }
      }
    };

    return Connection;

  })();

  module.exports = Connection;

}).call(this);
