// Generated by CoffeeScript 1.10.0
(function() {
  var e, error;

  module.exports = {
    connection: {
      host: '127.0.0.1',
      port: 9090
    }
  };

  try {
    module.exports = require('./config.local');
  } catch (error) {
    e = error;
  }

}).call(this);
