// Generated by CoffeeScript 1.10.0
(function() {
  var TCPConnection, Table, XbmcApi, config, connection, ref, table, xbmcApi;

  Table = require('cli-table');

  ref = require('..'), TCPConnection = ref.TCPConnection, XbmcApi = ref.XbmcApi;

  config = require('./config');

  connection = new TCPConnection({
    host: config.connection.host,
    port: config.connection.port,
    verbose: true
  });

  xbmcApi = new XbmcApi({
    silent: true,
    connection: connection
  });

  xbmcApi.media.movies({
    properties: ['genre', 'year']
  });

  table = new Table({
    head: ['#', 'Label', 'Genre', 'Year']
  });

  table.options.style.compact = true;

  xbmcApi.on('api:movies', function(movies) {
    var i, len, movie;
    console.log(movies.length + " Movies");
    for (i = 0, len = movies.length; i < len; i++) {
      movie = movies[i];
      table.push([movie.movieid, movie.label, movie.genre.join(', '), movie.year]);
    }
    return console.log(table.toString());
  });

}).call(this);
