// Generated by CoffeeScript 1.4.0
(function() {
  var TCPConnection, Table, XbmcApi, config, connection, table, xbmcApi, _ref;

  Table = require('cli-table');

  _ref = require('..'), TCPConnection = _ref.TCPConnection, XbmcApi = _ref.XbmcApi;

  config = require('./config');

  connection = new TCPConnection({
    host: config.connection.host,
    port: config.connection.port,
    verbose: true
  });

  xbmcApi = new XbmcApi({
    silent: true,
    connection: connection
  });

  xbmcApi.media.movies({
    properties: ['genre', 'year']
  });

  table = new Table({
    head: ['#', 'Label', 'Genre', 'Year']
  });

  table.options.style.compact = true;

  xbmcApi.on('api:movies', function(movies) {
    var movie, _i, _len;
    console.log("" + movies.length + " Movies");
    for (_i = 0, _len = movies.length; _i < _len; _i++) {
      movie = movies[_i];
      table.push([movie.movieid, movie.label, movie.genre.join(', '), movie.year]);
    }
    return console.log(table.toString());
  });

}).call(this);
