// Generated by CoffeeScript 1.4.0
(function() {
  var TCPConnection, Table, XbmcApi, connection, xbmcApi, _ref;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  Table = require('cli-table');

  _ref = require('..'), TCPConnection = _ref.TCPConnection, XbmcApi = _ref.XbmcApi;

  connection = new TCPConnection({
    host: '127.0.0.1',
    port: 9090,
    verbose: false
  });

  xbmcApi = new XbmcApi({
    silent: true,
    connection: connection
  });

  xbmcApi.media.movies({
    properties: ['genre', 'year']
  });

  xbmcApi.on('api:movies', function(movies) {
    var movie, table, _i, _len;
    console.log("" + movies.length + " Movies");
    table = new Table({
      head: ['#', 'Label', 'Genre', 'Year']
    });
    table.options.style.compact = true;
    for (_i = 0, _len = movies.length; _i < _len; _i++) {
      movie = movies[_i];
      table.push([movie.movieid, movie.label, movie.genre.join(', '), movie.year]);
    }
    return console.log(table.toString());
  });

}).call(this);
