// Generated by CoffeeScript 1.4.0
(function() {
  var TCPConnection, XbmcApi, connection, xbmcApi, _ref;

  _ref = require('..'), TCPConnection = _ref.TCPConnection, XbmcApi = _ref.XbmcApi;

  connection = new TCPConnection({
    host: '127.0.0.1',
    port: 9090,
    verbose: false
  });

  xbmcApi = new XbmcApi({
    silent: true,
    connection: connection
  });

  xbmcApi.player.openYoutube('QH2-TGUlwu4');

}).call(this);
