// Generated by CoffeeScript 1.4.0
(function() {
  var TCPConnection, Table, XbmcApi, connection, query, re, table, xbmcApi, _ref;

  Table = require('cli-table');

  _ref = require('..'), TCPConnection = _ref.TCPConnection, XbmcApi = _ref.XbmcApi;

  connection = new TCPConnection({
    host: '127.0.0.1',
    port: 9090,
    verbose: false
  });

  xbmcApi = new XbmcApi({
    silent: true,
    connection: connection
  });

  xbmcApi.media.movies({
    properties: ['genre', 'year']
  });

  query = process.argv[2];

  re = new RegExp(query, "i");

  table = new Table({
    head: ['#', 'Label', 'Genre', 'Year']
  });

  table.options.style.compact = true;

  xbmcApi.on('api:movies', function(movies) {
    var movie, _i, _len;
    for (_i = 0, _len = movies.length; _i < _len; _i++) {
      movie = movies[_i];
      if (movie.label.match(re)) {
        table.push([movie.movieid, movie.label, movie.genre.join(', '), movie.year]);
      }
    }
    console.log("" + table.length + " Movies");
    return console.log(table.toString());
  });

}).call(this);
