// Generated by CoffeeScript 1.4.0
(function() {
  var TCPConnection, Table, XbmcApi, config, connection, query, re, table, xbmcApi, _ref;

  Table = require('cli-table');

  _ref = require('..'), TCPConnection = _ref.TCPConnection, XbmcApi = _ref.XbmcApi;

  config = require('./config');

  connection = new TCPConnection({
    host: config.connection.host,
    port: config.connection.port,
    verbose: false
  });

  xbmcApi = new XbmcApi({
    silent: true,
    connection: connection
  });

  xbmcApi.media.movies({
    properties: ['file']
  });

  query = process.argv[2];

  re = new RegExp(query, "i");

  table = new Table({
    head: ['#', 'Label']
  });

  table.options.style.compact = true;

  xbmcApi.on('api:movies', function(movies) {
    var movie, _i, _len;
    for (_i = 0, _len = movies.length; _i < _len; _i++) {
      movie = movies[_i];
      if (movie.label.match(re)) {
        table.push([movie.movieid, movie.label, movie.file]);
      }
    }
    console.log("" + table.length + " Movies");
    console.log(table.toString());
    return xbmcApi.disconnect(function() {
      return process.exit(0);
    })();
  });

}).call(this);
