// Generated by CoffeeScript 1.10.0
(function() {
  var TCPConnection, Table, XbmcApi, config, connection, query, re, ref, table, xbmcApi;

  Table = require('cli-table');

  ref = require('..'), TCPConnection = ref.TCPConnection, XbmcApi = ref.XbmcApi;

  config = require('./config');

  connection = new TCPConnection({
    host: config.connection.host,
    port: config.connection.port,
    verbose: false
  });

  xbmcApi = new XbmcApi({
    silent: true,
    connection: connection
  });

  xbmcApi.media.movies({
    properties: ['file']
  });

  query = process.argv[2];

  re = new RegExp(query, "i");

  table = new Table({
    head: ['#', 'Label']
  });

  table.options.style.compact = true;

  xbmcApi.on('api:movies', function(movies) {
    var i, len, movie;
    for (i = 0, len = movies.length; i < len; i++) {
      movie = movies[i];
      if (movie.label.match(re)) {
        table.push([movie.movieid, movie.label, movie.file]);
      }
    }
    console.log(table.length + " Movies");
    console.log(table.toString());
    return xbmcApi.disconnect(function() {
      return process.exit(0);
    })();
  });

}).call(this);
